{
	"id": "ALSA-2021:1578",
	"title": "Important: kernel security, bug fix, and enhancement update",
	"description": "The kernel packages contain the Linux kernel, the core of any Linux operating system.\n\nSecurity Fix(es):\n\n* kernel: Integer overflow in Intel(R) Graphics Drivers (CVE-2020-12362)\n\n* kernel: memory leak in sof_set_get_large_ctrl_data() function in sound/soc/sof/ipc.c (CVE-2019-18811)\n\n* kernel: use-after-free caused by a malicious USB device in the drivers/usb/misc/adutux.c driver (CVE-2019-19523)\n\n* kernel: use-after-free bug caused by a malicious USB device in the drivers/usb/misc/iowarrior.c driver (CVE-2019-19528)\n\n* kernel: possible out of bounds write in kbd_keycode of keyboard.c (CVE-2020-0431)\n\n* kernel: DoS by corrupting mountpoint reference counter (CVE-2020-12114)\n\n* kernel: use-after-free in usb_sg_cancel function in drivers/usb/core/message.c (CVE-2020-12464)\n\n* kernel: buffer uses out of index in ext3/4 filesystem (CVE-2020-14314)\n\n* kernel: Use After Free vulnerability in cgroup BPF component (CVE-2020-14356)\n\n* kernel: NULL pointer dereference in serial8250_isa_init_ports function in drivers/tty/serial/8250/8250_core.c (CVE-2020-15437)\n\n* kernel: umask not applied on filesystem without ACL support (CVE-2020-24394)\n\n* kernel: TOCTOU mismatch in the NFS client code (CVE-2020-25212)\n\n* kernel: incomplete permission checking for access to rbd devices (CVE-2020-25284)\n\n* kernel: race condition between hugetlb sysctl handlers in mm/hugetlb.c (CVE-2020-25285)\n\n* kernel: improper input validation in ppp_cp_parse_cr function leads to memory corruption and read overflow (CVE-2020-25643)\n\n* kernel: perf_event_parse_addr_filter memory (CVE-2020-25704)\n\n* kernel: use-after-free in kernel midi subsystem (CVE-2020-27786)\n\n* kernel: child process is able to access parent mm through hfi dev file handle (CVE-2020-27835)\n\n* kernel: slab-out-of-bounds read in fbcon (CVE-2020-28974)\n\n* kernel: fork: fix copy_process(CLONE_PARENT) race with the exiting ->real_parent (CVE-2020-35508)\n\n* kernel: fuse: fuse_do_getattr() calls make_bad_inode() in inappropriate situations (CVE-2020-36322)\n\n* kernel: use after free in tun_get_user of tun.c could lead to local escalation of privilege (CVE-2021-0342)\n\n* kernel: NULL pointer dereferences in ov511_mode_init_regs and ov518_mode_init_regs in drivers/media/usb/gspca/ov519.c (CVE-2020-11608)\n\nFor more details about the security issue(s), including the impact, a CVSS score, acknowledgments, and other related information, refer to the CVE page(s) listed in the References section.\n\nAdditional Changes:\n\nFor detailed information on changes in this release, see the AlmaLinux Release Notes linked from the References section.",
	"affected": [
		{
			"vulnerable": true,
			"package": {
				"ecosystem": "AlmaLinux:8",
				"name": "kernel-tools-libs-devel"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "4.18.0-305.el8"
						}
					]
				}
			]
		}
	],
	"vulnerabilities": [
		{
			"cve": "CVE-2020-0431",
			"references": [
				{
					"name": "CVE-2020-0431",
					"source": "errata.almalinux.org",
					"tags": [
						"cve"
					],
					"url": "https://vulners.com/cve/CVE-2020-0431"
				}
			]
		},
		{
			"cve": "CVE-2020-14314",
			"references": [
				{
					"name": "CVE-2020-14314",
					"source": "errata.almalinux.org",
					"tags": [
						"cve"
					],
					"url": "https://vulners.com/cve/CVE-2020-14314"
				}
			]
		},
		{
			"cve": "CVE-2020-24394",
			"references": [
				{
					"name": "CVE-2020-24394",
					"source": "errata.almalinux.org",
					"tags": [
						"cve"
					],
					"url": "https://vulners.com/cve/CVE-2020-24394"
				}
			]
		},
		{
			"cve": "CVE-2020-25212",
			"references": [
				{
					"name": "CVE-2020-25212",
					"source": "errata.almalinux.org",
					"tags": [
						"cve"
					],
					"url": "https://vulners.com/cve/CVE-2020-25212"
				}
			]
		},
		{
			"cve": "CVE-2020-28974",
			"references": [
				{
					"name": "CVE-2020-28974",
					"source": "errata.almalinux.org",
					"tags": [
						"cve"
					],
					"url": "https://vulners.com/cve/CVE-2020-28974"
				}
			]
		},
		{
			"cve": "CVE-2020-12362",
			"references": [
				{
					"name": "CVE-2020-12362",
					"source": "errata.almalinux.org",
					"tags": [
						"cve"
					],
					"url": "https://vulners.com/cve/CVE-2020-12362"
				}
			]
		},
		{
			"cve": "CVE-2020-14356",
			"references": [
				{
					"name": "CVE-2020-14356",
					"source": "errata.almalinux.org",
					"tags": [
						"cve"
					],
					"url": "https://vulners.com/cve/CVE-2020-14356"
				}
			]
		},
		{
			"cve": "CVE-2020-25704",
			"references": [
				{
					"name": "CVE-2020-25704",
					"source": "errata.almalinux.org",
					"tags": [
						"cve"
					],
					"url": "https://vulners.com/cve/CVE-2020-25704"
				}
			]
		},
		{
			"cve": "CVE-2020-35508",
			"references": [
				{
					"name": "CVE-2020-35508",
					"source": "errata.almalinux.org",
					"tags": [
						"cve"
					],
					"url": "https://vulners.com/cve/CVE-2020-35508"
				}
			]
		},
		{
			"cve": "CVE-2020-36322",
			"references": [
				{
					"name": "CVE-2020-36322",
					"source": "errata.almalinux.org",
					"tags": [
						"cve"
					],
					"url": "https://vulners.com/cve/CVE-2020-36322"
				}
			]
		},
		{
			"cve": "CVE-2019-18811",
			"references": [
				{
					"name": "CVE-2019-18811",
					"source": "errata.almalinux.org",
					"tags": [
						"cve"
					],
					"url": "https://vulners.com/cve/CVE-2019-18811"
				}
			]
		},
		{
			"cve": "CVE-2019-19523",
			"references": [
				{
					"name": "CVE-2019-19523",
					"source": "errata.almalinux.org",
					"tags": [
						"cve"
					],
					"url": "https://vulners.com/cve/CVE-2019-19523"
				}
			]
		},
		{
			"cve": "CVE-2019-19528",
			"references": [
				{
					"name": "CVE-2019-19528",
					"source": "errata.almalinux.org",
					"tags": [
						"cve"
					],
					"url": "https://vulners.com/cve/CVE-2019-19528"
				}
			]
		},
		{
			"cve": "CVE-2020-12114",
			"references": [
				{
					"name": "CVE-2020-12114",
					"source": "errata.almalinux.org",
					"tags": [
						"cve"
					],
					"url": "https://vulners.com/cve/CVE-2020-12114"
				}
			]
		},
		{
			"cve": "CVE-2020-12464",
			"references": [
				{
					"name": "CVE-2020-12464",
					"source": "errata.almalinux.org",
					"tags": [
						"cve"
					],
					"url": "https://vulners.com/cve/CVE-2020-12464"
				}
			]
		},
		{
			"cve": "CVE-2020-15437",
			"references": [
				{
					"name": "CVE-2020-15437",
					"source": "errata.almalinux.org",
					"tags": [
						"cve"
					],
					"url": "https://vulners.com/cve/CVE-2020-15437"
				}
			]
		},
		{
			"cve": "CVE-2021-0342",
			"references": [
				{
					"name": "CVE-2021-0342",
					"source": "errata.almalinux.org",
					"tags": [
						"cve"
					],
					"url": "https://vulners.com/cve/CVE-2021-0342"
				}
			]
		},
		{
			"cve": "CVE-2020-11608",
			"references": [
				{
					"name": "CVE-2020-11608",
					"source": "errata.almalinux.org",
					"tags": [
						"cve"
					],
					"url": "https://vulners.com/cve/CVE-2020-11608"
				}
			]
		},
		{
			"cve": "CVE-2020-25284",
			"references": [
				{
					"name": "CVE-2020-25284",
					"source": "errata.almalinux.org",
					"tags": [
						"cve"
					],
					"url": "https://vulners.com/cve/CVE-2020-25284"
				}
			]
		},
		{
			"cve": "CVE-2020-25285",
			"references": [
				{
					"name": "CVE-2020-25285",
					"source": "errata.almalinux.org",
					"tags": [
						"cve"
					],
					"url": "https://vulners.com/cve/CVE-2020-25285"
				}
			]
		},
		{
			"cve": "CVE-2020-25643",
			"references": [
				{
					"name": "CVE-2020-25643",
					"source": "errata.almalinux.org",
					"tags": [
						"cve"
					],
					"url": "https://vulners.com/cve/CVE-2020-25643"
				}
			]
		},
		{
			"cve": "CVE-2020-27786",
			"references": [
				{
					"name": "CVE-2020-27786",
					"source": "errata.almalinux.org",
					"tags": [
						"cve"
					],
					"url": "https://vulners.com/cve/CVE-2020-27786"
				}
			]
		},
		{
			"cve": "CVE-2020-27835",
			"references": [
				{
					"name": "CVE-2020-27835",
					"source": "errata.almalinux.org",
					"tags": [
						"cve"
					],
					"url": "https://vulners.com/cve/CVE-2020-27835"
				}
			]
		}
	],
	"references": [
		{
			"name": "CVE-2020-0431",
			"source": "errata.almalinux.org",
			"tags": [
				"cve"
			],
			"url": "https://vulners.com/cve/CVE-2020-0431"
		},
		{
			"name": "CVE-2020-12363",
			"source": "errata.almalinux.org",
			"tags": [
				"cve"
			],
			"url": "https://vulners.com/cve/CVE-2020-12363"
		},
		{
			"name": "CVE-2020-12464",
			"source": "errata.almalinux.org",
			"tags": [
				"cve"
			],
			"url": "https://vulners.com/cve/CVE-2020-12464"
		},
		{
			"name": "CVE-2020-25284",
			"source": "errata.almalinux.org",
			"tags": [
				"cve"
			],
			"url": "https://vulners.com/cve/CVE-2020-25284"
		},
		{
			"name": "CVE-2020-28974",
			"source": "errata.almalinux.org",
			"tags": [
				"cve"
			],
			"url": "https://vulners.com/cve/CVE-2020-28974"
		},
		{
			"name": "CVE-2020-35508",
			"source": "errata.almalinux.org",
			"tags": [
				"cve"
			],
			"url": "https://vulners.com/cve/CVE-2020-35508"
		},
		{
			"name": "CVE-2021-0342",
			"source": "errata.almalinux.org",
			"tags": [
				"cve"
			],
			"url": "https://vulners.com/cve/CVE-2021-0342"
		},
		{
			"name": "CVE-2019-19523",
			"source": "errata.almalinux.org",
			"tags": [
				"cve"
			],
			"url": "https://vulners.com/cve/CVE-2019-19523"
		},
		{
			"name": "CVE-2020-15437",
			"source": "errata.almalinux.org",
			"tags": [
				"cve"
			],
			"url": "https://vulners.com/cve/CVE-2020-15437"
		},
		{
			"name": "CVE-2020-25212",
			"source": "errata.almalinux.org",
			"tags": [
				"cve"
			],
			"url": "https://vulners.com/cve/CVE-2020-25212"
		},
		{
			"name": "CVE-2020-25704",
			"source": "errata.almalinux.org",
			"tags": [
				"cve"
			],
			"url": "https://vulners.com/cve/CVE-2020-25704"
		},
		{
			"name": "CVE-2020-25643",
			"source": "errata.almalinux.org",
			"tags": [
				"cve"
			],
			"url": "https://vulners.com/cve/CVE-2020-25643"
		},
		{
			"name": "CVE-2020-27786",
			"source": "errata.almalinux.org",
			"tags": [
				"cve"
			],
			"url": "https://vulners.com/cve/CVE-2020-27786"
		},
		{
			"name": "CVE-2020-25285",
			"source": "errata.almalinux.org",
			"tags": [
				"cve"
			],
			"url": "https://vulners.com/cve/CVE-2020-25285"
		},
		{
			"name": "CVE-2020-36322",
			"source": "errata.almalinux.org",
			"tags": [
				"cve"
			],
			"url": "https://vulners.com/cve/CVE-2020-36322"
		},
		{
			"name": "CVE-2021-0605",
			"source": "errata.almalinux.org",
			"tags": [
				"cve"
			],
			"url": "https://vulners.com/cve/CVE-2021-0605"
		},
		{
			"name": "CVE-2019-18811",
			"source": "errata.almalinux.org",
			"tags": [
				"cve"
			],
			"url": "https://vulners.com/cve/CVE-2019-18811"
		},
		{
			"name": "CVE-2020-12114",
			"source": "errata.almalinux.org",
			"tags": [
				"cve"
			],
			"url": "https://vulners.com/cve/CVE-2020-12114"
		},
		{
			"name": "CVE-2020-14356",
			"source": "errata.almalinux.org",
			"tags": [
				"cve"
			],
			"url": "https://vulners.com/cve/CVE-2020-14356"
		},
		{
			"name": "CVE-2020-24394",
			"source": "errata.almalinux.org",
			"tags": [
				"cve"
			],
			"url": "https://vulners.com/cve/CVE-2020-24394"
		},
		{
			"name": "CVE-2020-11608",
			"source": "errata.almalinux.org",
			"tags": [
				"cve"
			],
			"url": "https://vulners.com/cve/CVE-2020-11608"
		},
		{
			"name": "CVE-2019-19528",
			"source": "errata.almalinux.org",
			"tags": [
				"cve"
			],
			"url": "https://vulners.com/cve/CVE-2019-19528"
		},
		{
			"name": "CVE-2020-14314",
			"source": "errata.almalinux.org",
			"tags": [
				"cve"
			],
			"url": "https://vulners.com/cve/CVE-2020-14314"
		},
		{
			"name": "CVE-2020-27835",
			"source": "errata.almalinux.org",
			"tags": [
				"cve"
			],
			"url": "https://vulners.com/cve/CVE-2020-27835"
		},
		{
			"name": "CVE-2020-12362",
			"source": "errata.almalinux.org",
			"tags": [
				"cve"
			],
			"url": "https://vulners.com/cve/CVE-2020-12362"
		},
		{
			"name": "CVE-2020-12364",
			"source": "errata.almalinux.org",
			"tags": [
				"cve"
			],
			"url": "https://vulners.com/cve/CVE-2020-12364"
		}
	],
	"published": "2021-05-18T05:33:57Z",
	"modified": "2021-08-11T08:54:00Z",
	"data_source": "alma-osv"
}
