{
	"id": "ALSA-2022:8162",
	"title": "Moderate: 389-ds-base security, bug fix, and enhancement update",
	"description": "389 Directory Server is an LDAP version 3 (LDAPv3) compliant server. The base packages include the Lightweight Directory Access Protocol (LDAP) server and command-line utilities for server administration.\n\nThe following packages have been upgraded to a later upstream version: 389-ds-base (2.1.3). (BZ#2061801)\n\nSecurity Fix(es):\n\n* 389-ds-base: sending crafted message could result in DoS (CVE-2022-0918)\n* 389-ds-base: SIGSEGV in sync_repl (CVE-2022-2850)\n* 389-ds-base: expired password was still allowed to access the database (CVE-2022-0996)\n\nFor more details about the security issue(s), including the impact, a CVSS score, acknowledgments, and other related information, refer to the CVE page(s) listed in the References section.\n\nAdditional Changes:\n\nFor detailed information on changes in this release, see the AlmaLinux Release Notes linked from the References section.",
	"affected": [
		{
			"vulnerable": true,
			"package": {
				"ecosystem": "AlmaLinux:9",
				"name": "389-ds-base"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "2.1.3-4.el9_1"
						}
					]
				}
			]
		},
		{
			"vulnerable": true,
			"package": {
				"ecosystem": "AlmaLinux:9",
				"name": "389-ds-base-libs"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "2.1.3-4.el9_1"
						}
					]
				}
			]
		},
		{
			"vulnerable": true,
			"package": {
				"ecosystem": "AlmaLinux:9",
				"name": "python3-lib389"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "2.1.3-4.el9_1"
						}
					]
				}
			]
		}
	],
	"vulnerabilities": [
		{
			"cve": "CVE-2022-0996",
			"references": [
				{
					"name": "CVE-2022-0996",
					"source": "errata.almalinux.org",
					"tags": [
						"cve"
					],
					"url": "https://access.redhat.com/security/cve/CVE-2022-0996"
				}
			]
		},
		{
			"cve": "CVE-2022-2850",
			"references": [
				{
					"name": "CVE-2022-2850",
					"source": "errata.almalinux.org",
					"tags": [
						"cve"
					],
					"url": "https://access.redhat.com/security/cve/CVE-2022-2850"
				}
			]
		},
		{
			"cve": "CVE-2022-0918",
			"references": [
				{
					"name": "CVE-2022-0918",
					"source": "errata.almalinux.org",
					"tags": [
						"cve"
					],
					"url": "https://access.redhat.com/security/cve/CVE-2022-0918"
				}
			]
		}
	],
	"references": [
		{
			"name": "CVE-2022-0918",
			"source": "errata.almalinux.org",
			"tags": [
				"cve"
			],
			"url": "https://access.redhat.com/security/cve/CVE-2022-0918"
		},
		{
			"name": "CVE-2022-0996",
			"source": "errata.almalinux.org",
			"tags": [
				"cve"
			],
			"url": "https://access.redhat.com/security/cve/CVE-2022-0996"
		},
		{
			"name": "CVE-2022-2850",
			"source": "errata.almalinux.org",
			"tags": [
				"cve"
			],
			"url": "https://access.redhat.com/security/cve/CVE-2022-2850"
		},
		{
			"name": "2055815",
			"source": "errata.almalinux.org",
			"tags": [
				"bugzilla"
			],
			"url": "https://bugzilla.redhat.com/2055815"
		},
		{
			"name": "2064769",
			"source": "errata.almalinux.org",
			"tags": [
				"bugzilla"
			],
			"url": "https://bugzilla.redhat.com/2064769"
		},
		{
			"name": "2118691",
			"source": "errata.almalinux.org",
			"tags": [
				"bugzilla"
			],
			"url": "https://bugzilla.redhat.com/2118691"
		},
		{
			"name": "ALSA-2022-8162",
			"source": "errata.almalinux.org",
			"tags": [
				"vendor-advisory"
			],
			"url": "https://errata.almalinux.org/9/ALSA-2022-8162.html"
		},
		{
			"name": "RHSA-2022:8162",
			"source": "errata.almalinux.org",
			"tags": [
				"third-party-advisory"
			],
			"url": "https://access.redhat.com/errata/RHSA-2022:8162"
		}
	],
	"published": "2022-11-15T00:00:00Z",
	"modified": "2022-11-18T03:52:36Z",
	"data_source": "alma-osv"
}
