{
	"id": "ALSA-2022:8353",
	"title": "Moderate: python3.9 security, bug fix, and enhancement update",
	"description": "Python is an interpreted, interactive, object-oriented programming language, which includes modules, classes, exceptions, very high level dynamic data types and dynamic typing. Python supports interfaces to many system calls and libraries, as well as to various windowing systems.\n\nThe following packages have been upgraded to a later upstream version: python3.9 (3.9.14). (BZ#2128249)\n\nSecurity Fix(es):\n\n* python: mailcap: findmatch() function does not sanitize the second argument (CVE-2015-20107)\n* python: open redirection vulnerability in lib/http/server.py may lead to information disclosure (CVE-2021-28861)\n\nFor more details about the security issue(s), including the impact, a CVSS score, acknowledgments, and other related information, refer to the CVE page(s) listed in the References section.\n\nAdditional Changes:\n\nFor detailed information on changes in this release, see the AlmaLinux Release Notes linked from the References section.",
	"affected": [
		{
			"vulnerable": true,
			"package": {
				"ecosystem": "AlmaLinux:9",
				"name": "python-unversioned-command"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "3.9.14-1.el9"
						}
					]
				}
			]
		},
		{
			"vulnerable": true,
			"package": {
				"ecosystem": "AlmaLinux:9",
				"name": "python3"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "3.9.14-1.el9"
						}
					]
				}
			]
		},
		{
			"vulnerable": true,
			"package": {
				"ecosystem": "AlmaLinux:9",
				"name": "python3-debug"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "3.9.14-1.el9"
						}
					]
				}
			]
		},
		{
			"vulnerable": true,
			"package": {
				"ecosystem": "AlmaLinux:9",
				"name": "python3-devel"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "3.9.14-1.el9"
						}
					]
				}
			]
		},
		{
			"vulnerable": true,
			"package": {
				"ecosystem": "AlmaLinux:9",
				"name": "python3-idle"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "3.9.14-1.el9"
						}
					]
				}
			]
		},
		{
			"vulnerable": true,
			"package": {
				"ecosystem": "AlmaLinux:9",
				"name": "python3-libs"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "3.9.14-1.el9"
						}
					]
				}
			]
		},
		{
			"vulnerable": true,
			"package": {
				"ecosystem": "AlmaLinux:9",
				"name": "python3-test"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "3.9.14-1.el9"
						}
					]
				}
			]
		},
		{
			"vulnerable": true,
			"package": {
				"ecosystem": "AlmaLinux:9",
				"name": "python3-tkinter"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "3.9.14-1.el9"
						}
					]
				}
			]
		}
	],
	"vulnerabilities": [
		{
			"cve": "CVE-2021-28861",
			"references": [
				{
					"name": "CVE-2021-28861",
					"source": "errata.almalinux.org",
					"tags": [
						"cve"
					],
					"url": "https://access.redhat.com/security/cve/CVE-2021-28861"
				}
			]
		},
		{
			"cve": "CVE-2015-20107",
			"references": [
				{
					"name": "CVE-2015-20107",
					"source": "errata.almalinux.org",
					"tags": [
						"cve"
					],
					"url": "https://access.redhat.com/security/cve/CVE-2015-20107"
				}
			]
		}
	],
	"references": [
		{
			"name": "CVE-2021-28861",
			"source": "errata.almalinux.org",
			"tags": [
				"cve"
			],
			"url": "https://access.redhat.com/security/cve/CVE-2021-28861"
		},
		{
			"name": "2075390",
			"source": "errata.almalinux.org",
			"tags": [
				"bugzilla"
			],
			"url": "https://bugzilla.redhat.com/2075390"
		},
		{
			"name": "2120642",
			"source": "errata.almalinux.org",
			"tags": [
				"bugzilla"
			],
			"url": "https://bugzilla.redhat.com/2120642"
		},
		{
			"name": "ALSA-2022-8353",
			"source": "errata.almalinux.org",
			"tags": [
				"vendor-advisory"
			],
			"url": "https://errata.almalinux.org/9/ALSA-2022-8353.html"
		},
		{
			"name": "RHSA-2022:8353",
			"source": "errata.almalinux.org",
			"tags": [
				"third-party-advisory"
			],
			"url": "https://access.redhat.com/errata/RHSA-2022:8353"
		},
		{
			"name": "CVE-2015-20107",
			"source": "errata.almalinux.org",
			"tags": [
				"cve"
			],
			"url": "https://access.redhat.com/security/cve/CVE-2015-20107"
		}
	],
	"published": "2022-11-15T00:00:00Z",
	"modified": "2022-11-18T13:19:27Z",
	"data_source": "alma-osv"
}
